version: "3"

services:
  docker-3:
    container_name: docker-3
    image: jedha/lab-docker-3
    hostname: jedha-vps
    ports:
      - "${DOCKER_EVASION_2_SSH_PORT}:2222"
    privileged: true
    mac_address: 9c:b6:d0:10:22:14
    networks:
      lab-inner-network:
        ipv4_address: 10.10.200.10

networks:
  lab-inner-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.200.0/24
