version: "3"

services:
  m03-d13-docker-3:
    container_name: m03-d13-docker-3
    image: jedha/lab-docker-3
    hostname: jedha-vps
    privileged: true
    mac_address: 9c:b6:d0:10:22:14
    networks:
      m03-d13-docker-network:
        ipv4_address: 10.10.200.10
networks:
  m03-d13-docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.200.0/24
