version: "3"

services:
  m03-d13-docker-1:
    container_name: m03-d13-docker-1
    image: jedha/lab-docker-1
    mac_address: 9c:b6:d0:12:0f:34
    hostname: jail1
    networks:
      m03-network:
        ipv4_address: 10.10.3.37
      m03-d13-docker-network:
        ipv4_address: 10.10.200.143

  m03-d13-docker-2:
    container_name: m03-d13-docker-2
    image: jedha/lab-docker-2
    hostname: host
    mac_address: 9c:b6:d0:32:9f:12
    networks:
      m03-d13-docker-network:
        ipv4_address: 10.10.200.52

networks:
  m03-d13-docker-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.200.0/24

  m03-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
