version: "3"

services:
  m03-d12-format-string:
    container_name: m03-d12-format-string
    image: jedha/lab-format-string
    expose:
      - "1339"
    restart: always
    networks:
      m03-network:
        ipv4_address: 10.10.3.36

networks:
  m03-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
