version: "3"

services:
  m03-d14-bluetooth-bettercap:
    container_name: m03-d14-bluetooth-bettercap
    image: jedha/lab-bluetooth-bettercap
    hostname: bettercap
    networks:
      m03-network:
        ipv4_address: 10.10.3.38

networks:
  m03-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
