version: "3"

services:
  m03-d05-idor:
    container_name: m03-d05-idor
    image: jedha/lab-idor
    hostname: jedha-bootcamp
    expose:
      - 80
    entrypoint: python3 /app/app.py
    networks:
      m03-network:
        ipv4_address: 10.10.3.18

networks:
  m03-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
