version: "3"

services:
  m03-d06-insecure-design:
    container_name: m03-d06-insecure-design
    image: jedha/lab-insecure-design
    hostname: jedha-bootcamp
    expose:
      - 80
    networks:
      m03-network:
        ipv4_address: 10.10.3.22

networks:
  m03-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
