version: "3"

services:
  m03-d07-linux-privesc:
    container_name: m03-d07-linux-privesc
    image: jedha/lab-linux-privesc
    hostname: linux4
    networks:
      m03-network:
        ipv4_address: 10.10.3.27

  m03-d07-linux-privesc-project-1:
    container_name: m03-d07-linux-privesc-project-1
    image: jedha/lab-linux-privesc-project-1
    networks:
      m03-network:
        ipv4_address: 10.10.3.28

  m03-d07-linux-privesc-project-2:
    container_name: m03-d07-linux-privesc-project-2
    image: jedha/lab-linux-privesc-project-2
    networks:
      m03-network:
        ipv4_address: 10.10.3.29

  m03-d07-linux-privesc-project-3:
    container_name: m03-d07-linux-privesc-project-3
    image: jedha/lab-linux-privesc-project-3
    networks:
      m03-network:
        ipv4_address: 10.10.3.30

networks:
  m03-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
