version: "3"

services:
  m03-d05-path-traversal:
    container_name: m03-d05-path-traversal
    image: jedha/lab-path-traversal
    hostname: jedha-bootcamp
    expose:
      - 80
    networks:
      m03-network:
        ipv4_address: 10.10.3.19
networks:
  m03-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
