version: "3"

services:
  m03-d03-pentest-network-ftp:
    container_name: m03-d03-pentest-network-ftp
    image: jedha/lab-pentest-network-ftp
    expose:
      - "21"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.2

  m03-d03-pentest-network-proxychains:
    container_name: m03-d03-pentest-network-proxychains
    image: jedha/lab-pentest-network-proxychains
    expose:
      - "22"
      - "80"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.3

  m03-d03-pentest-network-ssh:
    container_name: m03-d03-pentest-network-ssh
    image: jedha/lab-pentest-network-ssh
    expose:
      - "22"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.5

  m03-d03-pentest-network-telnet:
    container_name: m03-d03-pentest-network-telnet
    image: jedha/lab-pentest-network-telnet
    hostname: JEDHA{Qu1te_0ld_But_St1ll_3xists}
    expose:
      - "23"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.113

  m03-d03-pentest-network-nginx:
    container_name: m03-d03-pentest-network-nginx
    image: jedha/lab-pentest-network-nginx
    expose:
      - "80"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.207

  m03-d03-pentest-network-nginx-2:
    container_name: m03-d03-pentest-network-nginx-2
    image: jedha/lab-pentest-network-nginx-2
    ports:
      - "81:80"
    netwoks:
      m03-d03-network:
        ipv4_address: 10.10.30.138

  m03-d03-pentest-network-apache:
    container_name: m03-d03-pentest-network-apache
    image: jedha/lab-pentest-network-apache
    ports:
      - "8000:80"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.50

  m03-d03-pentest-network-squid:
    container_name: m03-d03-pentest-network-squid
    image: jedha/lab-pentest-network-squid
    expose:
      - "3128"
    hostname: JEDHA{Why_N0t_ProxY}
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.55

  m03-d03-pentest-network-smb:
    container_name: m03-d03-pentest-network-smb
    image: jedha/lab-pentest-network-smb
    tty: true
    expose:
      - "139"
      - "445"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.150

  m03-d03-pentest-network-mysql:
    container_name: m03-d03-pentest-network-mysql
    image: jedha/lab-pentest-network-mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    networks:
      m03-d03-network:
        ipv4_address: 10.10.30.201
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

networks:
  m03-d03-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.30.0/24
