version: "3"

services:
  m03-d04-sqli:
    container_name: m03-d04-sqli
    image: jedha/lab-sqli
    hostname: jedha-bootcamp
    depends_on:
      - m03-d04-sqli-mysql
    expose:
      - 80
    networks:
      m03-network:
        ipv4_address: 10.10.3.14
      m03-d04-sqli-network:

  m03-d04-sqli-mysql:
    container_name: m03-d04-sqli-mysql
    image: jedha/lab-sqli-mysql
    hostname: jedha-bootcamp
    environment:
      MYSQL_DATABASE: sqli
      MYSQL_ROOT_PASSWORD: XCG45DzjNCWzjC3QAynDQtaoVqCe
      MYSQL_USER: jedha
      MYSQL_PASSWORD: XCG45DzjNCWzjC3QAynDQtaoVqCe
    expose:
      - 3306
    networks:
      m03-d04-sqli-network:

networks:
  m03-d04-sqli-network:
    driver: bridge

  m03-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
