version: "3"

services:
  m03-d08-suid:
    container_name: m03-d08-suid
    image: jedha/lab-suid
    expose:
      - "22"
    networks:
      m03-network:
        ipv4_address: 10.10.3.31

networks:
  m03-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
