version: "3"

services:
  m03-d04-ssti-java-thymeleaf:
    container_name: m03-d04-ssti-java-thymeleaf
    image: jedha/lab-ssti-java-thymeleaf
    hostname: jedha-bootcamp
    expose:
      - 80
    networks:
      m03-network:
        ipv4_address: 10.10.3.16

  m03-d04-ssti-python-jinja2:
    container_name: m03-d04-ssti-python-jinja2
    image: jedha/lab-ssti-python-jinja2
    hostname: jedha-bootcamp
    expose:
      - 80
    entrypoint: python3 /root/server.py
    networks:
      m03-network:
        ipv4_address: 10.10.3.17

networks:
  m03-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
