version: "3"

services:
  ssti-java-thymeleaf:
    container_name: ssti-java-thymeleaf
    image: jedha/lab-ssti-java-thymeleaf
    hostname: jedha-bootcamp
    ports:
      - "${SSTI_THYMELEAF_PORT}:80"
    networks:
      lab-network:
        ipv4_address: 10.10.3.16

  ssti-python-jinja2:
    container_name: ssti-python-jinja2
    image: jedha/lab-ssti-python-jinja2
    hostname: jedha-bootcamp
    ports:
      - "${SSTI_JINJA_PORT}:80"
    entrypoint: python3 /root/server.py
    networks:
      lab-network:
        ipv4_address: 10.10.3.17

networks:
  lab-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
