version: "3"

services:
  gash:
    container_name: vim
    image: jedha/lab-vim
    networks:
      lab-network:
        ipv4_address: 10.10.3.81
    ports:
      - "22"

networks:
  lab-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.3.0/24
