version: "3"

services:
  aircrack:
    container_name: aircrack
    image: jedha/lab-aircrack
    hostname: wifi-pineapple
    ports:
      - "${WIFI_WPA2_CRACKING_SSH_PORT}:22"
    networks:
      lab-network:
        ipv4_address: 10.10.3.47

networks:
  lab-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.3.0/24
